In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("./train_test_practice_data.csv")
df.head(1)

,student_id,study_hours_per_week,attendance_rate,previous_grade,tutoring_sessions,sleep_hours_per_night,parental_education,internet_access,exam_score,passed_exam
0,STD_1000,10.7,98.0,56.9,2,6.4,Bachelor,Yes,62.0,0

In [3]:
X=df[['study_hours_per_week', 'attendance_rate', 'previous_grade']]
y=df["passed_exam"]

In [4]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=20)

In [9]:
len(X_train)

280

In [10]:
len(X_test)

70

In [17]:
X_train, X_test, y_tarin, y_test = train_test_split(X,y,test_size=0.2,random_state=20)
X_train

     study_hours_per_week  attendance_rate  previous_grade
53                    9.7             72.9            79.0
156                  12.4             93.0            35.0
286                  19.4             60.3            54.9
29                   14.4             91.9            89.2
62                    7.2             89.8            55.2
..                    ...              ...             ...
278                  11.2             86.0            50.8
331                   8.1             89.2            75.9
218                  10.7             80.4            63.9
223                   1.5             79.2            73.6
271                   9.1             88.1            52.4

[280 rows x 3 columns]